spring.application.name=membership-program

spring.datasource.url=jdbc:h2:mem:membershipdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

tier.criteria.rules.silver.min-order-count=5
tier.criteria.rules.silver.min-order-value=1000
tier.criteria.rules.silver.eligible-cohorts=

tier.criteria.rules.gold.min-order-count=15
tier.criteria.rules.gold.min-order-value=5000
tier.criteria.rules.gold.eligible-cohorts=

tier.criteria.rules.platinum.min-order-count=30
tier.criteria.rules.platinum.min-order-value=15000
tier.criteria.rules.platinum.eligible-cohorts[0]=PREMIUM
tier.criteria.rules.platinum.eligible-cohorts[1]=VIP
